apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskit-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskit
  template:
    metadata:
      labels:
        app: taskit
    spec:
      containers:
      - name: taskit
        image: ghcr.io/drjonesii/taskit:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_ENV
          value: "production"
        - name: DJANGO_DEBUG
          value: "False"
        - name: POSTGRES_DB
          value: "your_database_name"
        - name: POSTGRES_USER
          value: "your_database_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
